chunk_size: 256
max_num_local_file: 4096
max_local_disk_size: 100
sys_config_path: "/dev/null"
storage_backend: "tutti_ub"
extra_config:
  tutti_endpoint: "127.0.0.1:50051"
  tutti_device_ids: [0, 1, 2, 3]
  tutti_owners: [0, 1, 0, 1]
  tutti_descriptor: "sgl"
  tutti_queues: 16
  tutti_max_entries_per_batch: 4096
  tutti_defer_sync: false
  tutti_bulk_load: true
